name: publish pyright-python

on:
  push:
    branches:
      - main
    paths:
      - "src/pyright/_version.py"
  workflow_dispatch:

jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install -r dev-requirements.txt

      - name: Download pyright dist
        run: |
          python scripts/download_pyright.py

      - name: Get version
        run: |
          echo "NEW_VERSION=$(python .github/scripts/get_version.py --compare)" >> $GITHUB_ENV

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel
      
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: 'v${{ env.NEW_VERSION }}'
          tag: 'v${{ env.NEW_VERSION }}'
          file: dist/*.whl
          overwrite: true
          file_glob: true
